resources:
- repo: self
queue:
  name: Hosted VS2017
  demands: DotNetFramework

steps:
- task: NuGetCommand@2
  inputs:
    vstsFeed: '73b462b3-f7d1-4d50-afc6-4c357fefba75'

- task: DownloadSecureFile@1
  inputs:
    secureFile: wetcon_codesign_July_2021.pfx

- powershell: |
    $env:SignCertPath=$env:DOWNLOADSECUREFILE_SECUREFILEPATH
    ./build.ps1 --Target Build --Sign
  displayName: Build with cake
  env: 
    SignCertPassword: $(SignCertPassword)
    SignCertTimeStampUri: $(SignCertTimeStampUri)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'artifacts/Wetcon.PactwarePlugin.OpcUaServer.Setup'
    ArtifactName: Setup
    publishLocation: Container

