resources:
- repo: self
pool:
  vmImage: 'windows-2022'

steps:
# - task: NuGetCommand@2
#   inputs:
#     vstsFeed: '73b462b3-f7d1-4d50-afc6-4c357fefba75'

- task: DownloadSecureFile@1
  inputs:
    secureFile: wetcon_codesign_July_2021.pfx

- powershell: |
    $env:SignCertPath=$env:DOWNLOADSECUREFILE_SECUREFILEPATH
    ./build.PW5.ps1 --Target Default --Sign
  displayName: Build with cake
  env: 
    SignCertPassword: $(SignCertPassword)
    SignCertTimeStampUri: $(SignCertTimeStampUri)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'artifacts/Wetcon.PactwarePlugin.OpcUaServer.Setup/PW5'
    ArtifactName: SetupPW5
    publishLocation: Container

- powershell: |
    $env:SignCertPath=$env:DOWNLOADSECUREFILE_SECUREFILEPATH
    ./build.PW6.ps1 --Target Default --Sign
  displayName: Build with cake
  env: 
    SignCertPassword: $(SignCertPassword)
    SignCertTimeStampUri: $(SignCertTimeStampUri)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'artifacts/Wetcon.PactwarePlugin.OpcUaServer.Setup/PW6'
    ArtifactName: SetupPW6
    publishLocation: Container

