<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>OPCUA2AWSIOT</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>7.1</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Wetcon.OpcUaClient.Base\Wetcon.OpcUaClient.Base.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.IotData">
      <Version>4.0.0.4</Version>
    </PackageReference>
  </ItemGroup>
</Project>
