<xs:schema
  xmlns:Opc.Ua.DI="http://opcfoundation.org/UA/DI/"
  xmlns:Opc.Ua.IA="http://opcfoundation.org/UA/IA/"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:ua="http://opcfoundation.org/UA/2008/02/Types.xsd"
  xmlns:tns="http://opcfoundation.org/UA/Machinery/"
  targetNamespace="http://opcfoundation.org/UA/Machinery/"
  elementFormDefault="qualified"
>
  <xs:annotation>
    <xs:appinfo>
      <ua:Model ModelUri="http://opcfoundation.org/UA/Machinery/" Version="1.04.1" PublicationDate="2026-01-01T00:00:00Z" />
    </xs:appinfo>
  </xs:annotation>
  
  <xs:import namespace="http://opcfoundation.org/UA/" />
  <xs:import namespace="http://opcfoundation.org/UA/DI/" />
  <xs:import namespace="http://opcfoundation.org/UA/IA/" />

</xs:schema>