<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>LoadTest</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>7.1</LangVersion>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject>Wetcon.OpcUaClient.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Wetcon.OpcUaClient.Base\Wetcon.OpcUaClient.Base.csproj" />
  </ItemGroup>
</Project>
