//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("wetcon gmbh")]
[assembly: AssemblyProduct("OpcUaServerPlugin")]
[assembly: AssemblyVersion("1.0.9.0")]
[assembly: AssemblyFileVersion("1.0.9.0")]
[assembly: AssemblyInformationalVersion("1.0.9+Branch.master.Sha.6bb1f6dd55652c423f00aa283202e0f0a11bfb36")]
[assembly: AssemblyCopyright("Copyright (c) wetcon gmbh 2019 - 2025")]

