//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("wetcon gmbh")]
[assembly: AssemblyProduct("OpcUaServerPlugin")]
[assembly: AssemblyVersion("1.0.10.0")]
[assembly: AssemblyFileVersion("1.0.10.0")]
[assembly: AssemblyInformationalVersion("1.0.10+Branch.feature/upgrade-2026.Sha.c361ee0ae015069fde3cca1b6b85fa421f7e30d3")]
[assembly: AssemblyCopyright("Copyright (c) wetcon gmbh 2019 - 2026")]

